export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETIALS_REQUEST = "USER_DETIALS_REQUEST";
export const USER_DETIALS_SUCCESS = "USER_DETIALS_SUCCESS";
export const USER_DETIALS_FAIL = "USER_DETIALS_FAIL";
export const USER_DETIALS_RESET = "USER_DETIALS_RESET";
